services:
  - type: web
    name: jarvis-cloud
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=10000"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CHAVE_FIREBASE_BASE64
        sync: false
    pythonVersion: 3.11.6
