services:
  - type: web
    name: jarvis-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ELEVEN_API_KEY
        sync: false
      - key: ELEVEN_VOICE_ID
        sync: false
